spec:
  destination:
    server: "https://api.oc46-devel.cloudlet-dev.com:6443"
    namespace: "argo-to-argo-app"
  source:
    repoURL: https://github.com/christianh814/gitops-examples
    targetRevision: HEAD
  project: default
  labelKey: test
  labelValue: dev
generator:
  name: "{{name}}"
  server: "{{server}}"
appsetNamespace: openshift-gitops
