spec:
  destination:
    server: "https://api.oc46-devel.cloudlet-dev.com:6443"
    namespace: "argo-to-argo-app"
  source:
    path: 04.Application-Lifecycle/exercise-argocd/application-resources/values/*
    repoURL: https://github.com/michaelkotelnikov/rhacm-workshop
    targetRevision: HEAD
  project: default
  labelKey: test
  labelValue: dev
generator:
  name: "{{name}}"
  server: "{{server}}"
  valuefile: "{{path.basename}}"
appsetNamespace: openshift-gitops
