apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: testing-appset-appset
  namespace: {{ .Values.appsetNamespace }}
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            {{ .Values.spec.labelKey }}: {{ .Values.spec.labelValue }}
  template:
    metadata:
      name: '{{ .Values.generator.name }}-test'
    spec:
      destination:
        namespace: appset-declarative-test
        server: '{{ .Values.generator.server }}'
      project: default
      source:
        path: {{ .Values.spec.source.path }}
        repoURL: {{ .Values.spec.source.repoURL }}
        targetRevision: master
        helm:
          valueFiles:
          - 'values/{{path.basename}}/values.yaml'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
